spring:
  rabbitmq:
    host: localhost
    username: gridcapa
    password: gridcapa
    port: 5672
  cloud:
    stream:
      bindings:
        run-task:
          binder: rabbit
          destination: core-valid-run-task

job-launcher:
  task-manager-url: http://localhost/core/valid/task-manager/tasks/
