spring:
  cloud:
    function:
      definition: consumeTaskDtoUpdate

gridcapa-version: 5.15.0

job-launcher:
  auto: false
  process:
    timezone: CET
    days-to-add: 0

scheduler:
  enable: false

retry:
  backoff:
    delay: 10000 # 10s delay before first retry
    multiplier: 2
  max-attempts: 5 # the first attempt + 4 potential retry
