logback:
  amqp:
    exchange: task-manager-logs-exchange
    routing-key: "#"
spring:
  application:
    name: gridcapa-job-launcher
  rabbitmq:
    host: localhost
    username: gridcapa
    password: gridcapa
    port: 5672
  cloud:
    stream:
      bindings:
        run-task:
          destination: cse-d2cc-run-task
          group: cse-d2cc-job-launcher
      rabbit:
        default:
          consumer:
            auto-bind-dlq: true
            max-attempts: 1

job-launcher:
  task-manager-url: http://localhost:8080/tasks/

scheduler:
  enable: true
  start-hour: 0
  end-hour: 20
  cronjob: "* */2 ${scheduler.start-hour}-${scheduler.end-hour} * * *"
